SELECT * 
FROM STUDENT
WHERE STATUS  = TRUE;
SELECT * 
FROM SUBJECT 
WHERE CREDIT < 10;
SELECT S.STUDENTID, S.STUDENTNAME, C.CLASSNAME
FROM STUDENT S JOIN CLASS C ON S.CLASSID = C.CLASSID
WHERE CLASSNAME = 'A1';
SELECT S.STUDENTID, S.STUDENTNAME, SUB.SUBNAME, M.MARK
FROM STUDENT S JOIN MARK M ON S.STUDENTID = M.STUDENTID JOIN SUBJECT SUB ON SUB.SUBID = M.SUBID
WHERE SUBNAME = 'CF';